[package]
name = "duckbill"
version = "0.1.0"
authors = ["Maxwell I. French <maxwell@frenchnet.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
