[package]
name = "duckbill"
version = "0.2.0"
authors = ["Maxwell French <maxwell@frenchnet.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
